// <auto-generated />
using System;
using EMSI_Corporation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMSI_Corporation.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMSI_Corporation.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumCelular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Comprobante", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComprobante"));

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NroComprobante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Venta_ID")
                        .HasColumnType("integer");

                    b.HasKey("IdComprobante");

                    b.HasIndex("Venta_ID");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.ComprobanteServicio", b =>
                {
                    b.Property<int>("IdComprobante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdComprobante"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdComprobante");

                    b.ToTable("ComprobantesServicio");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("apeEmpleado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("gmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nomEmpleado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("numCelular")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("IdEmpleado");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("EMSI_Corporation.Models.EventoCalendario", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvento"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("IdEvento");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("EventosCalendario");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Extintor", b =>
                {
                    b.Property<int>("IdExtintor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdExtintor"));

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("integer");

                    b.Property<decimal>("CapacidadKG")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ClaseFuego")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RecepcionId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoAgente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Venta_ID")
                        .HasColumnType("integer");

                    b.HasKey("IdExtintor");

                    b.HasIndex("RecepcionId");

                    b.HasIndex("Venta_ID");

                    b.ToTable("Extintores");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.InformeTecnico", b =>
                {
                    b.Property<int>("IdInforme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInforme"));

                    b.Property<DateTime>("FechaInforme")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Informe_PDF")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Visita_ID")
                        .HasColumnType("integer");

                    b.HasKey("IdInforme");

                    b.HasIndex("Visita_ID");

                    b.ToTable("InformesTecnicos");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Mantenimiento", b =>
                {
                    b.Property<int>("IdMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMantenimiento"));

                    b.Property<bool>("AperturaCorrecta")
                        .HasColumnType("boolean");

                    b.Property<bool>("BarometroCorrecto")
                        .HasColumnType("boolean");

                    b.Property<bool>("BoquillaCorrecta")
                        .HasColumnType("boolean");

                    b.Property<int>("Empleado_ID")
                        .HasColumnType("integer");

                    b.Property<bool>("EstadoIndicador")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstadoPrecinto")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExteriorCorrecto")
                        .HasColumnType("boolean");

                    b.Property<int>("Extintor_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaMantenimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InstruccionesVisibles")
                        .HasColumnType("boolean");

                    b.Property<bool>("LugarAdecuado")
                        .HasColumnType("boolean");

                    b.Property<bool>("MangueraCorrecta")
                        .HasColumnType("boolean");

                    b.Property<bool>("PesoCorrecto")
                        .HasColumnType("boolean");

                    b.Property<bool>("PresionCorrecta")
                        .HasColumnType("boolean");

                    b.Property<int?>("ReporteServicioIdReporte")
                        .HasColumnType("integer");

                    b.Property<int>("ReporteServicio_ID")
                        .HasColumnType("integer");

                    b.Property<bool>("Señalización")
                        .HasColumnType("boolean");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean");

                    b.HasKey("IdMantenimiento");

                    b.HasIndex("Empleado_ID");

                    b.HasIndex("Extintor_ID");

                    b.HasIndex("ReporteServicioIdReporte");

                    b.HasIndex("ReporteServicio_ID");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMenu"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("nomMenu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdMenu");

                    b.ToTable("Menu", (string)null);
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Proovedor", b =>
                {
                    b.Property<int>("IdProovedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProovedor"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumCelular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("estado")
                        .HasColumnType("boolean");

                    b.HasKey("IdProovedor");

                    b.ToTable("Proovedor", (string)null);
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Recarga", b =>
                {
                    b.Property<int>("IdRecarga")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecarga"));

                    b.Property<decimal>("CantidadKG")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Empleado_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Extintor_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaRecarga")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MaterialUsado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PresionPostRecarga")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ReporteServicioIdReporte")
                        .HasColumnType("integer");

                    b.Property<int>("ReporteServicio_ID")
                        .HasColumnType("integer");

                    b.HasKey("IdRecarga");

                    b.HasIndex("Empleado_ID");

                    b.HasIndex("Extintor_ID");

                    b.HasIndex("ReporteServicioIdReporte");

                    b.HasIndex("ReporteServicio_ID");

                    b.ToTable("Recargas");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Recepcion", b =>
                {
                    b.Property<int>("IdRecepcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRecepcion"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProovedorId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("IdRecepcion");

                    b.HasIndex("ProovedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Recepcion", (string)null);
                });

            modelBuilder.Entity("EMSI_Corporation.Models.ReporteServicio", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReporte"));

                    b.Property<int>("Cliente_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Comprobante_ID")
                        .HasColumnType("integer");

                    b.Property<byte[]>("FirmaCliente")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<byte[]>("ImgEvidencia")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdReporte");

                    b.HasIndex("Cliente_ID");

                    b.HasIndex("Comprobante_ID");

                    b.ToTable("ReportesServicio");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("nomRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Rol_Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdMenu", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("Rol_Menu", (string)null);
                });

            modelBuilder.Entity("EMSI_Corporation.Models.User_Rol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("IdUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("User_Rol", (string)null);
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("integer");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEmpleado")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVenta"));

                    b.Property<int>("Cliente_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Empleado_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdVenta");

                    b.HasIndex("Cliente_ID");

                    b.HasIndex("Empleado_ID");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.VisitaTecnica", b =>
                {
                    b.Property<int>("IdVisita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVisita"));

                    b.Property<int>("Cliente_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Empleado_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdVisita");

                    b.HasIndex("Cliente_ID");

                    b.HasIndex("Empleado_ID");

                    b.ToTable("VisitasTecnicas");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Comprobante", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("Venta_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.EventoCalendario", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Extintor", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Recepcion", "Recepcion")
                        .WithMany()
                        .HasForeignKey("RecepcionId");

                    b.HasOne("EMSI_Corporation.Models.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("Venta_ID");

                    b.Navigation("Recepcion");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.InformeTecnico", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.VisitaTecnica", "VisitaTecnica")
                        .WithMany()
                        .HasForeignKey("Visita_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitaTecnica");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Mantenimiento", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("Empleado_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMSI_Corporation.Models.Extintor", "Extintor")
                        .WithMany()
                        .HasForeignKey("Extintor_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EMSI_Corporation.Models.ReporteServicio", null)
                        .WithMany("Mantenimientos")
                        .HasForeignKey("ReporteServicioIdReporte");

                    b.HasOne("EMSI_Corporation.Models.ReporteServicio", "ReporteServicio")
                        .WithMany()
                        .HasForeignKey("ReporteServicio_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Extintor");

                    b.Navigation("ReporteServicio");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Recarga", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("Empleado_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMSI_Corporation.Models.Extintor", "Extintor")
                        .WithMany()
                        .HasForeignKey("Extintor_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EMSI_Corporation.Models.ReporteServicio", null)
                        .WithMany("Recargas")
                        .HasForeignKey("ReporteServicioIdReporte");

                    b.HasOne("EMSI_Corporation.Models.ReporteServicio", "ReporteServicio")
                        .WithMany()
                        .HasForeignKey("ReporteServicio_ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Extintor");

                    b.Navigation("ReporteServicio");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Recepcion", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Proovedor", "Proovedor")
                        .WithMany("Recepciones")
                        .HasForeignKey("ProovedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EMSI_Corporation.Models.Usuario", "Usuario")
                        .WithMany("Recepciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Proovedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.ReporteServicio", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Cliente_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMSI_Corporation.Models.ComprobanteServicio", "ComprobanteServicio")
                        .WithMany()
                        .HasForeignKey("Comprobante_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ComprobanteServicio");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Rol_Menu", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Menu", "Menu")
                        .WithMany("RolMenus")
                        .HasForeignKey("IdMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMSI_Corporation.Models.Rol", "Rol")
                        .WithMany("RolMenus")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.User_Rol", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Rol", "Rol")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMSI_Corporation.Models.Usuario", "Usuario")
                        .WithMany("UserRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Usuario", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Empleado", "empleado")
                        .WithOne("usuario")
                        .HasForeignKey("EMSI_Corporation.Models.Usuario", "IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("empleado");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Venta", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Cliente_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMSI_Corporation.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("Empleado_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.VisitaTecnica", b =>
                {
                    b.HasOne("EMSI_Corporation.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Cliente_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EMSI_Corporation.Models.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("Empleado_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Empleado", b =>
                {
                    b.Navigation("usuario")
                        .IsRequired();
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Menu", b =>
                {
                    b.Navigation("RolMenus");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Proovedor", b =>
                {
                    b.Navigation("Recepciones");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.ReporteServicio", b =>
                {
                    b.Navigation("Mantenimientos");

                    b.Navigation("Recargas");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Rol", b =>
                {
                    b.Navigation("RolMenus");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EMSI_Corporation.Models.Usuario", b =>
                {
                    b.Navigation("Recepciones");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
